sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - develop
  - staging
  - QA

jobs:
  include:
    - stage: Web-Builder-Fronted-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t web_builder_fronted_flowz:latest --build-arg domainkey="$DOMAINKEY_MASTER" .;
            docker images;
            docker tag web_builder_fronted_flowz:latest $DOCKER_USERNAME_FLOWZ/web_builder_fronted_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/web_builder_fronted_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t web_builder_fronted_flowz:dev --build-arg domainkey="$DOMAINKEY_DEVELOP" .;
            docker images;
            docker tag web_builder_fronted_flowz:dev $DOCKER_USERNAME/web_builder_fronted_flowz:dev;
            docker push $DOCKER_USERNAME/web_builder_fronted_flowz:dev;
        elif [ ${TRAVIS_BRANCH} = "staging" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t web_builder_fronted_flowz:staging --build-arg domainkey="$DOMAINKEY_STAGING" .;
            docker tag web_builder_fronted_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/web_builder_fronted_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker tag web_builder_fronted_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/web_builder_fronted_flowz:staging;
            docker images;
            docker push $DOCKER_USERNAME/web_builder_fronted_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker push $DOCKER_USERNAME/web_builder_fronted_flowz:staging;    
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t web_builder_fronted_flowz:qa --build-arg domainkey="$DOMAINKEY_QA" .;
            docker images;
            docker tag web_builder_fronted_flowz:qa $DOCKER_USERNAME/web_builder_fronted_flowz:qa;
            docker push $DOCKER_USERNAME/web_builder_fronted_flowz:qa;
        fi'
    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - fsaiyed@officebrain.com
      - gkumar@officebrain.com
    on_success: always
    on_failure: always
